### ISSUE TITLE
Toast sites without pageWrapper result in <undefined> tags

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/toast#25]
cc/ @lannonbr

**Comment by lannonbr** [comment]
So there's a few issues through this:

1. When SSR is being done, there's not any error handling for the pageWrapper trying to be imported in the `incremental` command's script. So then when `render` is being called, it does a `h(undefined, data, h(components, ...))` This should be alright to solve by having a default wrapper as is done in the page-renderer code right now.
1. [page-renderer-pre.js](https://github.com/ChristopherBiscardi/toast/blob/master/packages/toast/src/page-renderer-pre.js) although is lacking some error handling so if any of the dynamic imports fail, it does not rehydrate clientside. The solution of this likely will have to be some tweaks to the logic in page-renderer-pre.
