### ISSUE TITLE
Exposing API access to Toast's babel config

### ISSUE THREAD

**Issue by lannonbr** [ChristopherBiscardi/toast#28]
To insert custom babel plugins for tools like inling SVGs, adding CSS-in-JS libraries, etc, it is needed to insert these babel plugins / presets into Toast's.

Currently you can do this by opening `node_modules/toast/src/transforms.js` in a toast site and adding the various babel plugins you need and then save the change with a tool like [patch-package](https://github.com/ds300/patch-package), but it would be better down the road to expose the babel config somehow to users.

**Comment by ChristopherBiscardi** [comment]
I think I'm going to advise patch-package for now until the Rust prototype is shipped since it moves us to swc.
