### ISSUE TITLE
automatically inject preload tags for page resources

### ISSUE THREAD

**Issue by jlengstorf** [ChristopherBiscardi/toast#29]
as a helpful performance boost, it would be nice to automatically inject a `<link rel="preload" />` for every resource loaded on a given page

<img width="938" alt="Screen Shot 2020-08-23 at 12 52 09 PM" src="https://user-images.githubusercontent.com/163561/90987460-030be400-e540-11ea-9e17-8468c8b0b8a1.png">

I'm not sure if this list of modules is already pulled up as Toast is building, but it would be nice if we could find those and auto-inject preloading tags for each resource

**Comment by ChristopherBiscardi** [comment]
We'll have to figure out how to dependency graph stuff before it's rendered to html, which I think is possible with SWC and some AST plugin import pulls mixed with computed queries from salsa's incremental computation graph. We should be able to like `db.graph()` and have that pull from the cache so we only calculate graphs once per file.

**Comment by ChristopherBiscardi** [comment]
Similar work: https://twitter.com/pikapkg/status/1305535312882327552?s=19

**Comment by ChristopherBiscardi** [comment]
Open question: how does this affect "minimal JavaScript" pages. One possible API for that includes different scripts running in the ssr process and client process.

**Comment by ChristopherBiscardi** [comment]
moved to new repo: https://github.com/toastdotdev/toast/issues/56
